### ISSUE TITLE
DB decision

### ISSUE THREAD

**Issue by HollyHutchings** [hres/vhpwebapp#1]
Decide if DB is mysql or postgres.

DECISION:  mysql

**Comment by BrainTrain3000** [comment]
Update: Decided to go with PostgreSQL instead of MySQL. It has features that make data of the complexity we're working with more manageable and straightforward. @ayoung8 will be applying this update to the system tomorrow.

**Comment by HollyHutchings** [comment]
Ok, thanks for this update and confirmation with Anthony.
